#!/bin/bash

CURRENT_TIMESTAMP=`date`
HOST_NAME=`hostname`

DIR=/root/sipp-3.7.3/

LOG_FILE=/tmp/SIPpWeekly3_LOG_INFO-$HOST_NAME.log


echo "==========================SIPp-BASIC-DATA===================================" >> $LOG_FILE


echo "***$CURRENT_TIMESTAMP - START OF LOG***" >> $LOG_FILE
echo "---------------------------------------------------------------------------------------" >> $LOG_FILE
echo "Hostname of this server is $HOST_NAME" >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE

echo "***CPU-INFO***" >> $LOG_FILE
lscpu >> $LOG_FILE

echo "=======================================================================================" >> $LOG_FILE
echo "***MEMORY-PRINTOUT***" >> $LOG_FILE
free -h >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE

echo "***OS-RELEASE***" >> $LOG_FILE
cat /etc/os-release >> $LOG_FILE
echo "---------------------------------------------------------------------------------------" >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE




echo "==========================SIPp-CALL-STARTED-$CURRENT_TIMESTAMP===================================" >> $LOG_FILE

cd $DIR

# Launch script in background
./sipp -sf uas-2reinv-pcmA.xml -i 10.61.13.183 -p 5060 &

# Get its PID for command above
PID=$!

echo "===The-PID-for-SIpp-is-$PID ===" >> $LOG_FILE


echo "===SIPp-PCM-CALLING-SBC28-10.61.13.202===" >> $LOG_FILE


./sipp -i 10.61.13.254 -p 5060 -sf uac-2reinv-pcmuA.xml -nr -m 500 -inf usercalls2000.csv -d 15000 -l 500 -r 50 -rp 1000 10.61.13.202:5060

sleep 5


echo "===SIPp-PCM-CALLING-SBC53-10.61.13.204===" >> $LOG_FILE

./sipp -i 10.61.13.254 -p 5060 -sf uac-2reinv-pcmuA.xml -nr -m 200 -inf usercalls2000.csv -d 15000 -l 500 -r 50 -rp 1000 10.61.13.204:5060


sleep 5


echo "===Killing-The-PID-for-SIpp-$PID ===" >> $LOG_FILE
kill -s SIGKILL $PID

# not used anymore
#kill -9 $(ps -ef | grep [s]ipp | awk '{print $2}')

sleep 20


./sipp -sf uas-2reinv-fax.xml -i 10.61.13.183 -p 5060 &


# Get its PID for command above
PID2=$!


echo "===SIPp-FAX-CALLING-SBC28-10.61.13.202===" >> $LOG_FILE

./sipp -i 10.61.13.254 -p 5060 -sf uac-2reinv-fax.xml -nr -m 1 -inf usercalls200.csv -d 10000 -l 15 10.61.13.202:5060 


sleep 5


echo "===SIPp-FAX-CALLING-SBC53-10.61.13.204===" >> $LOG_FILE

./sipp -i 10.61.13.254 -p 5060 -sf uac-2reinv-fax.xml -nr -m 1 -inf usercalls200.csv -d 10000 -l 15 10.61.13.204:5060 

echo "===Killing-The-PID-for-SIpp-$PID2 ===" >> $LOG_FILE
kill -s SIGKILL $PID2


sleep 20


./sipp -sf uas.xml -i 10.61.13.183 -p 5060 &


# Get its PID for command above
PID3=$!


echo "===SIPp-LONG-CALLING-SBC28-10.61.13.202===" >> $LOG_FILE

./sipp -i 10.61.13.254 -p 5060 -sf uac_usercalls.xml -nr -m 5 -inf usercalls200.csv -d 275000 -l 15 -r 10 10.61.13.202:5060


sleep 5


echo "===SIPp-LONG-CALLING-SBC53-10.61.13.204===" >> $LOG_FILE

./sipp -i 10.61.13.254 -p 5060 -sf uac_usercalls.xml -nr -m 5 -inf usercalls200.csv -d 395000 -l 15 -r 10 10.61.13.204:5060

echo "===Killing-The-PID-for-SIpp-$PID3 ===" >> $LOG_FILE
kill -s SIGKILL $PID3









echo "==========================SIPp-CALL-ENDED-$CURRENT_TIMESTAMP===================================" >> $LOG_FILE

chmod 755 $LOG_FILE

mv $LOG_FILE /tmp/SIPpWeekly3_LOG_INFO-$HOST_NAME-$(date +"%Y_%m_%d_%I_%M_%p").log

exit 0;


